### ISSUE TITLE
websockets dont work

### ISSUE THREAD

**Issue by neverender** [mauricemach/zappa#1]
The server side part looks like it works fine. But anytime I try to do any websocket stuff client-side, node crashes and I get this

undefined:1

SyntaxError: Unexpected token ILLEGAL
    at Object.parse (native)
    at /usr/local/lib/node/.npm/zappa/0.1.2/package/lib/zappa.coffee:584:16
    at [object Object].<anonymous> (/usr/local/lib/node/.npm/zappa/0.1.2/package/lib/zappa.coffee:185:17)
    at [object Object].<anonymous> (/usr/local/lib/node/.npm/zappa/0.1.2/package/lib/zappa.coffee:4:36)
    at [object Object].emit (events:27:15)
    at [object Object]._onMessage (/usr/local/lib/node/.npm/socket.io/0.6.1/package/lib/socket.io/client.js:53:10)
    at [object Object]._handle (/usr/local/lib/node/.npm/socket.io/0.6.1/package/lib/socket.io/transports/websocket.js:81:10)
    at Stream.<anonymous> (/usr/local/lib/node/.npm/socket.io/0.6.1/package/lib/socket.io/transports/websocket.js:63:10)
    at Stream.emit (events:27:15)
    at IOWatcher.callback (net:484:33)

My code works fine when I use socket.io normally.

**Comment by mauricemach** [comment]
Does /examples/websockets.coffee work for you?

**Comment by neverender** [comment]
Yes it does. I had some javascript already written that I didn't feel like converting to coffeescript, so I didn't use the 'client' thing. I just did a 'script src:' in the layout. Was that the problem?

**Comment by mauricemach** [comment]
Definitely not, you can use external js files fine.

From the info you gave me it seems the problem is in parsing the JSON you're sending the server. Are you sending valid JSON in the format `{"message_name": {"prop": "value"}}`?

**Comment by neverender** [comment]
I believe I was, but I've since redone it using your websockets example and that's good enough for me. I'll let you know if I come across the error again

**Comment by agnoster** [comment]
I had this problem when I was porting a pre-existing Node app to Zappa. First it happened because I was using socket.send() with an unencoded object. Then, it happened because I was sending a string with parseable-by-Javascript-but-not-valid-JSON like `{key: "value"}` instead of `{"key": "value"}`.

As long as you properly encode the payload, it should be fine.

**Comment by mauricemach** [comment]
Certainly doesn't help the fact that you have a nice comfy API on the server-side, but on the client you're left out in the cold. In a next version I plan to offer the same level of abstraction on the browser too with `msg`, `at`, `send`, etc and auto-parsing / auto-routing of messages. As an optional feature, of course.
