### ISSUE TITLE
"Can't use mutable header APIs after sent." on examples/async.coffee

### ISSUE THREAD

**Issue by sgtpep** [mauricemach/zappa#39]
Steps to reproduce:
Launch async.coffee from zappa's examples in Chrome (on Firefox it's OK). Try to get index page http://localhost:5678/ (not /bar). 

Exception traceback:

``` javascript
http.js:543

    throw new Error("Can't use mutable header APIs after sent.");

      ^

Error: Can't use mutable header APIs after sent.
    at ServerResponse.getHeader (http.js:543:11)
    at ServerResponse.header (/usr/lib/node_modules/zappa/node_modules/express/lib/response.js:241:17)
    at ServerResponse.send (/usr/lib/node_modules/zappa/node_modules/express/lib/response.js:66:17)
    at Object.render (/usr/lib/node_modules/zappa/lib/zappa.js:515:21)
    at Object.<anonymous> (eval at <anonymous> (/usr/lib/node_modules/zappa/lib/zappa.js:674:12))
    at Object._onTimeout (eval at <anonymous> (/usr/lib/node_modules/zappa/lib/zappa.js:674:12))
    at Timer.callback (timers.js:83:39)
```

**Comment by mauricemach** [comment]
Seems like it was a [node](https://github.com/joyent/node/issues/752) and [express](https://github.com/visionmedia/express/issues/561) issue.

**Comment by guiomie** [comment]
Any details on how you solved this error?

**Comment by mauricemach** [comment]
I didn't, it was at the node/express level, and it seems [TJ fixed it in express](https://github.com/visionmedia/express/issues/561#issuecomment-898748).

Node previously accepted multiple `next()` and `res.send()` calls failing silently, but after a commit started giving those errors. Express was changed not to do those multiple calls anymore.

I never had this issue since, but if you did, please let me know!

**Comment by guiomie** [comment]
I reorganized my code so multiple res.send() cant happen anymore. Thanks for you answer.

**Comment by mauricemach** [comment]
You're welcome!
