### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by DAddYE** [mauricemach/zappa#46]
Running:

```
$ zappa cuppa.coffe 
```

I get:

```
undefined:16
}; with(locals) {return (function () {get '/': 'hi'}).apply(context, args);}
                                          ^^^
SyntaxError: Unexpected string
    at Object.Function (unknown source)
    at /usr/local/lib/node_modules/zappa/lib/zappa.js:674:12
    at Zappa.define_with (/usr/local/lib/node_modules/zappa/lib/zappa.js:54:14)
    at Zappa.run (/usr/local/lib/node_modules/zappa/lib/zappa.js:88:12)
    at Zappa.run_file (/usr/local/lib/node_modules/zappa/lib/zappa.js:79:19)
    at Object.run_file (/usr/local/lib/node_modules/zappa/lib/zappa.js:700:23)
    at /usr/local/lib/node_modules/zappa/lib/cli.js:133:26
    at path.js:292:19
```

Every things works fine if I compile cuppa.coffe and then running it with node `node cuppa.js`

**Comment by DAddYE** [comment]
fuckme I forgot a `e` => `cuppa.coffee`
