### ISSUE TITLE
Error: EBADF, Bad file descriptor '/usr/local/lib/node/.npm/zappa/0.2.0beta/package/lib/../node_modules/jquery/dist/node-jquery.min.js' 

### ISSUE THREAD

**Issue by tcard** [mauricemach/zappa#51]
Just installed 0.2.0b via cloning this repo and npm'ing. This output is thrown whenever I try to run something.coffee:

```
Horchata:examples harad$ coffee hi.coffee
Error: EBADF, Bad file descriptor '/usr/local/lib/node/.npm/zappa/0.2.0beta/package/lib/../node_modules/jquery/dist/node-jquery.min.js'
    at Object.openSync (fs.js:221:18)
    at Object.readFileSync (fs.js:112:15)
    at Object.<anonymous> (/usr/local/lib/node/.npm/zappa/0.2.0beta/package/lib/zappa.js:19:15)
    at Object.<anonymous> (/usr/local/lib/node/.npm/zappa/0.2.0beta/package/lib/zappa.js:733:4)
    at Module._compile (module.js:402:26)
    at Object..js (module.js:408:10)
    at Module.load (module.js:334:31)
    at Function._load (module.js:293:12)
    at require (module.js:346:19)
    at Object.<anonymous> (/Users/harad/github/zappa/examples/hi.coffee:2:3)
```

Thanks in advance.

**Comment by mauricemach** [comment]
How did you "npm" it exactly? Here's what works for me:

```
git clone git://github.com/mauricemach/zappa.git
cd zappa
cake build
npm link

# This at whatever project you want to run with zappa.
# It's stupidly silly to install zappa at zappa's examples
# but that's how npm 1.x rolls, unless we want to require
# ../lib/zappa directly.
cd examples
npm link zappa
coffee hi.coffee
```

Your zappa is missing the jQuery dependency, which is installed for me at `npm link`. It's also strange that the version is `0.2.0beta`, since master is currently at `0.2.0beta2`.

**Comment by tcard** [comment]
OK, I was using npm 0.x, I don't know if it was truly incompatible but I updated and now works. Thanks!

**Comment by mauricemach** [comment]
No problem!

npm changes dramatically from 0.x to 1.x, I'd be surprised if it worked.
